### ISSUE TITLE
Intermittent MSpanList_Insert errors using Goon on MacOS Sierra

### ISSUE THREAD

**Issue by tmepple** [alco/goon#10]
I've been having many annoying and intermittent MSpanList_Insert errors when using Porcelain with the pre-compiled Goon driver (https://github.com/alco/goon/releases) on MacOS Sierra.  I would say my Elixir escript randomly failed ~20% of the time with this error.

Doing research, I found it's probably related to a bug in the older Golang compiler at https://github.com/golang/go/issues/17335 and https://github.com/golang/go/issues/17182 which was fixed (I think) in v1.8 of the compiler.

I made a very simple homebrew formula for Goon to compile locally using go 1.8.3 and install the HEAD version which has been working great for me with no errors, but I can't publish it in homebrew as Goon has <50 stars, <20 forks, and <20 watchers.  

In any event I think it would be good to release new v1.1.2 binaries compiled with the latest Golang at this point to help others with this issue.  Also doing this would close https://github.com/alco/goon/issues/8.

**Comment by tmepple** [comment]
Here is the homebrew formula I used to compile and install to solve my problem... I installed the HEAD version which also fixes the inconsistent version number issue #8.  I can't post this to homebrew as Goon is "not notable enough" unfortunately.  It requires the go compiler > 1.8 `brew install go` to be installed first.

https://gist.github.com/tmepple/9c2dd6d0ed2b5071a9efdb02e831e8f1

**Comment by alco** [comment]
I have rebuilt v1.1.1 using Go 19.3 and reuploaded all prebuilt binaries.
