### ISSUE TITLE
Trying to build from source fails on an M1 Mac

### ISSUE THREAD

**Issue by derheap** [alco/goon#11]
When I try to build from source on my M1 (ARM) MacBook Pro I get the following error:

~~~~
$ go build
go: cannot find main module
~~~~

**Comment by alco** [comment]
Hey @derheap. The source code for goon predates Go modules so it needs to be built in compatibility mode. I think the behaviour of `go build` has been changed only in a very recent release such that it now expects the `go.mod` file by default.

Try building goon with the `GO111MODULE` environment variable set to `off`. See https://go.dev/ref/mod#environment-variables for more info.

**Comment by derheap** [comment]
`GO111MODULE=off go build` worked like a charm!

Thanks!
