### ISSUE TITLE
add instructions to build from source on the readme

### ISSUE THREAD

**Issue by slashfoo** [alco/goon#2]
It'd be a nice-to-have™.

**Comment by alco** [comment]
Hey @slashfoo,

Sorry for a late reply, missed your message. Have you encountered any problems with building goon? Running `go build` works for me.

**Comment by slashfoo** [comment]
Ah, that worked, I didn't see the documentation anywhere. Thanks for getting back to me. And sorry for the late reply to the late reply :)

Maybe a note can be added to readme would help future visitors.

**Comment by alco** [comment]
I've added a mention of `go build` to the README. Thanks for bringing this up.
