### ISSUE TITLE
Latest v1.1.1 release is actually v1.1.0 for Darwin

### ISSUE THREAD

**Issue by whitfin** [alco/goon#8]
This seems to just be a mistake in uploads.

If you download the two darwin builds of goon from the releases (v1.1.1), they're actually v1.1.0 when you run `goon -v`.

**Comment by theowb4** [comment]
This is valid and just ate a decent bit of my dev time. Think we can get the releases updated @alco ?

**Comment by jbodah** [comment]
Any thoughts on this? We have some workarounds in our docs that I'd love to streamline

**Comment by cjbottaro** [comment]
Is this also the reason for this warning?
```[warn]  [Porcelain]: goon executable at /usr/local/bin/goon does not support protocol version 2.0```

**Comment by alco** [comment]
Sorry folks, I forgot to update the version number before doing the release.

@cjbottaro That must be something different because protocol 2.0 is supported since goon version 1.1.0. Regardless, I have reuploaded all prebuilt binaries for version 1.1.1.
